# Generated by Django 3.1.7 on 2021-04-12 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_Nacionalidad', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_Cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('documento', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='huesped.nacionalidad')),
            ],
        ),
    ]
